services:
  js-vue-web-frontend:
    container_name: js-vue-web-frontend
    build:
      context: ./docker/vue
      dockerfile: Dockerfile
    ports:
    - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    volumes:
      - ./frontend:/app
    environment:
    - APP_ENV=${APP_ENV}
    networks:
      - vite_network_local

  js-vue-web-mysql:
    image: 'mysql/mysql-server:8.0'
    container_name: js-vue-web-mysql
    ports:
      - '${FORWARD_DB_PORT:-3308}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'vite_mysql_local:/var/lib/mysql'
    networks:
      - vite_network_local
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s

  php-web-backend:
    restart: unless-stopped
    container_name: php-web-backend
    build:
      context: "./docker/php"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      XDEBUG_MODE: '${XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    expose:
      - "9000"
    volumes:
      - './backend/:/var/www/html'
    networks:
      - vite_network_local

  web-nginx:
    container_name: web-nginx
    image: nginx:latest
    volumes:
      - ./frontend/build:/usr/share/nginx/html/vue/build
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - vite_network_local

networks:
  vite_network_local:
    driver: bridge


volumes:
  vite_mysql_local:
    driver: local